/**
 * Small in-app EEG glossary. Tied to common terms in the UI. The popover
 * component uses this; the AI assistant also draws from it.
 */

export interface GlossaryEntry {
  term: string;
  short: string;
  detail: string;
  aliases?: string[];
}

export const GLOSSARY: GlossaryEntry[] = [
  {
    term: "Delta",
    short: "1–4 Hz · deep sleep, pathology, drift",
    detail:
      "Slowest classical EEG band. Dominant in N3 (deep sleep). In awake recordings, prominent delta is often baseline drift or pathology — verify the high-pass filter is set to ~0.5 Hz.",
  },
  {
    term: "Theta",
    short: "4–8 Hz · drowsy, meditation, memory",
    detail:
      "Linked to drowsiness, meditation, working memory, and frontal-midline executive activity. Elevated frontal theta is common during demanding cognitive tasks.",
  },
  {
    term: "Alpha",
    short: "8–13 Hz · resting wakefulness",
    detail:
      "Posterior dominant rhythm of relaxed wakefulness with eyes closed. Blocked by eye opening (Berger effect). Individual peak frequency (IAPF) is usually 9–11 Hz in healthy adults.",
    aliases: ["IAPF", "alpha peak"],
  },
  {
    term: "Beta",
    short: "13–30 Hz · active cognition, attention",
    detail:
      "Associated with active cognition, attention, motor planning, and anxiety. Above 20 Hz it's easily contaminated by EMG (jaw, neck, scalp muscles).",
  },
  {
    term: "Gamma",
    short: "30–45 Hz · attention / binding, often EMG",
    detail:
      "Tied in research to attention and neural binding. In scalp EEG, gamma is most often muscle artifact — check topography (broad/peripheral = EMG).",
  },
  {
    term: "Notch filter",
    short: "50/60 Hz line-noise suppressor",
    detail:
      "Narrow band-stop filter that removes AC mains contamination. Use 50 Hz in EU/India/most of Asia and Africa; 60 Hz in the Americas and parts of Asia.",
  },
  {
    term: "Band-pass filter",
    short: "Keeps a frequency range",
    detail:
      "Allows frequencies between two cut-offs to pass, attenuating everything else. Most EEG analysis uses 1–45 Hz; sleep often uses 0.3–35 Hz.",
  },
  {
    term: "High-pass filter",
    short: "Removes slow drift",
    detail:
      "Attenuates frequencies below a cut-off. 0.1–1 Hz preserves slow oscillations (delta); higher cut-offs distort ERP slow components.",
    aliases: ["HPF"],
  },
  {
    term: "Low-pass filter",
    short: "Removes high-frequency noise",
    detail:
      "Attenuates frequencies above a cut-off. 40–45 Hz is conventional; raise for gamma research; lower (30 Hz) to suppress EMG aggressively.",
    aliases: ["LPF"],
  },
  {
    term: "ICA",
    short: "Independent component analysis",
    detail:
      "Blind source separation that decomposes mixed EEG into statistically independent components. Used to remove eye/muscle artifacts by zeroing out the offending components.",
  },
  {
    term: "Topographic map",
    short: "Scalp projection of values",
    detail:
      "Projects per-channel values onto a head outline using their 10-20 positions, interpolating between electrodes to reveal spatial patterns.",
    aliases: ["topomap", "topography"],
  },
  {
    term: "PSD",
    short: "Power spectral density",
    detail:
      "Shows how signal power is distributed across frequencies. Usually computed with Welch's method: overlapping FFT windows averaged together.",
    aliases: ["Welch", "spectrum"],
  },
  {
    term: "Spectrogram",
    short: "Power vs frequency vs time",
    detail:
      "Time-frequency heatmap. Each column is a short-time FFT, showing how the spectrum changes over the recording. Useful for spotting drowsiness, eye-opening bursts, or seizures.",
  },
  {
    term: "Frontal alpha asymmetry",
    short: "FAA · affective valence proxy",
    detail:
      "log(right) − log(left) alpha power over F4/F3 (or homologous frontal pair). Larger right-lateralized alpha (= less right activity) → withdrawal/negative affect. Research-grade only.",
    aliases: ["FAA", "asymmetry"],
  },
  {
    term: "Sleep spindle",
    short: "11–16 Hz burst, ~0.5–2 s",
    detail:
      "Brief, waxing-and-waning burst in the sigma band. Diagnostic of N2 sleep. Generated by the thalamic reticular nucleus.",
  },
  {
    term: "K-complex",
    short: "Large biphasic deflection in N2",
    detail:
      "Sharp negative peak followed by a slower positive component, ≥100 µV. Marker of N2 sleep along with spindles.",
  },
  {
    term: "ERP",
    short: "Event-related potential",
    detail:
      "Time-locked, condition-averaged voltage waveform following a stimulus. Components like P300, N400, and ERN are the bread and butter of cognitive EEG.",
  },
  {
    term: "Sampling rate",
    short: "Samples per second (Hz)",
    detail:
      "How fast the amplifier digitizes the analog signal. Must be at least 2× the highest frequency of interest (Nyquist). Common values: 250, 500, 1000 Hz.",
  },
  {
    term: "Reference",
    short: "Where 'zero' is defined",
    detail:
      "EEG measures potential differences. The reference (mastoid, earlobe, average) determines what voltage means. Re-referencing can dramatically change topomaps.",
  },
  {
    term: "BIDS",
    short: "Brain Imaging Data Structure",
    detail:
      "A standard for organizing and describing neuroimaging datasets. BIDS-EEG specifies how channels, events, and metadata should be stored alongside recordings.",
  },
];

export function lookupTerm(term: string): GlossaryEntry | null {
  const t = term.trim().toLowerCase();
  for (const e of GLOSSARY) {
    if (e.term.toLowerCase() === t) return e;
    if (e.aliases?.some((a) => a.toLowerCase() === t)) return e;
  }
  return null;
}
